# Generated by Django 5.1.5 on 2025-01-21 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_employee_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='projects',
        ),
    ]
